server:
  port: 8080

endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false

#Database Configuration
db:
  driver: org.hsqldb.jdbc.JDBCDriver
  url: jdbc:hsqldb:mem:.
  username: sa
  password: 

#Hibernate Configuration
hibernate:
  dialect: org.hibernate.dialect.HSQLDialect
  hbm2ddl:
    auto: create
    import_files: import.sql
  ejb:
    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
  show_sql: false
  format_sql: true